### ISSUE TITLE
Basic copy rough draft

### ISSUE THREAD

**Issue by kylejonesdev** [kylejonesdev/pnwdevnetwork-website#1]
Develop a rough draft block of text talking about the purpose of the PNW Dev Network, who participates, regular events, and how to join.

**Comment by joshstruve** [comment]
The PNW Dev Network is a networking group and learning resource for web developers in the Pacific Northwest and beyond. Join us for coding help, design advice and networking opportunities.

**Comment by kylejonesdev** [comment]
Looks good. I'll add it in. Thanks.
