### ISSUE TITLE
Determine basic styling

### ISSUE THREAD

**Issue by kylejonesdev** [kylejonesdev/pnwdevnetwork-website#3]
Develop a basic style guide for the site. This includes color palette, font(s), header styling, and hero image.

**Comment by joshstruve** [comment]
![pnwdevnet-web-desktop](https://user-images.githubusercontent.com/63620595/217144280-dcaf6842-faf3-414d-9535-63a68d3b4040.png)
![pnwdevnet-web-mobile](https://user-images.githubusercontent.com/63620595/217144282-e5f613e4-adef-4b71-ae00-b3e7a3e59cc7.png)

**Comment by joshstruve** [comment]
Site background and logo
![pnwdevnetwork-logo](https://user-images.githubusercontent.com/63620595/217144638-d4b2069c-ce48-4797-9d5d-5c678308d904.png)
![pnwdevnet-site-bg](https://user-images.githubusercontent.com/63620595/217144640-686e6ef3-a62e-41c7-973d-091e33d8ea28.png)

**Comment by joshstruve** [comment]
**Typography**

- Logo/Header: [Braciola MS](https://www.cdnfonts.com/braciola-ms.font)
- Body: [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono)

**Colors:**

- Body Background (Behind the image): #101416
- Body Text (Primary): #FFFFFF
- Button Background (Primary): #B0FF4A
- Button Text (Primary): #101416
- Button Background (Secondary): #54A4B5
- Button Text (Secondary): #FFFFFF

**Comment by kylejonesdev** [comment]
Thanks again Josh. Great work. Designs implemented in #5.
